import random

products = [
    "Cadeira",
    "Mesa",
    "Fogão",
    "Geladeira",
    "Microondas",
    "Notebook",
    "Smartphone",
    "Tablet",
    "Cama",
    "Guarda-roupa",
    "Sofá",
    "Televisão",
    "Ventilador",
    "Ar-condicionado",
    "Cafeteira",
    "Liquidificador",
    "Ferro de passar",
    "Aspirador de pó",
    "Forno elétrico",
    "Panela elétrica",
    "Panela de pressão",
    "Batedeira",
    "Liquidificador",
    "Sanduicheira",
    "Torradeira",
    "Máquina de lavar",
    "Secadora de roupas",
    "Lava-louças",
    "Fritadeira elétrica",
    "Panela de arroz",
    "Grill",
    "Churrasqueira elétrica",
    "Forno micro-ondas",
    "Forno elétrico",
    "Forno a gás",
    "Fogão cooktop",
    "Fogão de embutir",
    "Fogão industrial",
    "Fogão a lenha",
    "Fogão a gás",
    "Fogão elétrico",
    "Fogão por indução",
    "Lasanha",
    "Pizza",
    "Hambúrguer",
    "Cachorro-quente",
    "Sushi",
    "Sashimi",
    "Yakissoba",
    "Nintendo Switch",
    "Playstation 5",
    "Xbox Series X",
    "Smart TV",
    "Smartwatch",
    "Relógio de pulso",
    "Relógio de parede",
    "Relógio de mesa",
    "Relógio de bolso",
    "Criança",
    "Adolescente",
    "Adulto",
    "Idoso",
    "Mulher",
    "Homem",
    "Menino",
    "Goiaba",
    "Manga",
    "Morango",
    "Banana",
    "Maçã",
    "Pera",
    "Uva"
]

qualities = [
    "Novo",
    "Usado",
    "Semi-novo",
    "Recertificado",
    "Recondicionado",
    "Restaurado",
    "Estragado", 
    "Quebrado",
    "Danificado",
    "Inutilizável",
    "Perfeito",
    "Excelente",
    "Dá pro gasto",
    "Ruim",
    "Péssimo",
    "Horrível",
    "Maravilhoso",
    "Fantástico",
    "Incrível",
    "Sensacional",
    "Extraordinário",
    "Magnífico",
    "Espetacular",
    "Deslumbrante",
    "Estonteante",
    "Indispensável",
    "Essencial",
    "Fundamental",
    "Necessário",
    "Obrigatório",
    "Dispensável",
    "Desnecessário",
    "Supérfluo",
    "Desimportante",
    "Irrelevante"
]

def create():
    return f"INSERT INTO product (name, price) VALUES ('{random.choice(products)} {random.choice(qualities)}', {random.randint(1, 100000)});\n"

def generate(n: int):
    with open('products_data.sql', 'w') as f:
        for i in range(n):
            f.write(create())

generate(100)
