INSERT INTO product (name, price) VALUES ('Televisão Semi-novo', 95620);
INSERT INTO product (name, price) VALUES ('Churrasqueira elétrica Dá pro gasto', 44491);
INSERT INTO product (name, price) VALUES ('Lava-louças Sensacional', 13145);
INSERT INTO product (name, price) VALUES ('Goiaba Novo', 71749);
INSERT INTO product (name, price) VALUES ('Lava-louças Novo', 33004);
INSERT INTO product (name, price) VALUES ('Batedeira Espetacular', 35559);
INSERT INTO product (name, price) VALUES ('Maçã Maravilhoso', 40166);
INSERT INTO product (name, price) VALUES ('Smart TV Essencial', 29467);
INSERT INTO product (name, price) VALUES ('Pizza Restaurado', 91578);
INSERT INTO product (name, price) VALUES ('Fogão a lenha Quebrado', 9626);
INSERT INTO product (name, price) VALUES ('Pizza Ruim', 42244);
INSERT INTO product (name, price) VALUES ('Relógio de mesa Danificado', 51107);
INSERT INTO product (name, price) VALUES ('Torradeira Ruim', 94279);
INSERT INTO product (name, price) VALUES ('Idoso Ruim', 34122);
INSERT INTO product (name, price) VALUES ('Hambúrguer Quebrado', 63069);
INSERT INTO product (name, price) VALUES ('Cachorro-quente Restaurado', 71339);
INSERT INTO product (name, price) VALUES ('Cadeira Danificado', 49907);
INSERT INTO product (name, price) VALUES ('Fogão industrial Ruim', 43609);
INSERT INTO product (name, price) VALUES ('Xbox Series X Estragado', 52189);
INSERT INTO product (name, price) VALUES ('Playstation 5 Dá pro gasto', 40500);
INSERT INTO product (name, price) VALUES ('Sushi Semi-novo', 79647);
INSERT INTO product (name, price) VALUES ('Torradeira Supérfluo', 19079);
INSERT INTO product (name, price) VALUES ('Nintendo Switch Estonteante', 58830);
INSERT INTO product (name, price) VALUES ('Sanduicheira Novo', 3376);
INSERT INTO product (name, price) VALUES ('Adolescente Fantástico', 63349);
INSERT INTO product (name, price) VALUES ('Banana Semi-novo', 75004);
INSERT INTO product (name, price) VALUES ('Goiaba Estonteante', 40449);
INSERT INTO product (name, price) VALUES ('Sofá Ruim', 91364);
INSERT INTO product (name, price) VALUES ('Cafeteira Novo', 45800);
INSERT INTO product (name, price) VALUES ('Lasanha Espetacular', 45148);
INSERT INTO product (name, price) VALUES ('Churrasqueira elétrica Irrelevante', 1370);
INSERT INTO product (name, price) VALUES ('Panela elétrica Essencial', 72912);
INSERT INTO product (name, price) VALUES ('Geladeira Espetacular', 41644);
INSERT INTO product (name, price) VALUES ('Relógio de pulso Supérfluo', 44715);
INSERT INTO product (name, price) VALUES ('Notebook Sensacional', 82174);
INSERT INTO product (name, price) VALUES ('Panela de arroz Essencial', 75053);
INSERT INTO product (name, price) VALUES ('Geladeira Recondicionado', 84118);
INSERT INTO product (name, price) VALUES ('Lasanha Obrigatório', 98369);
INSERT INTO product (name, price) VALUES ('Guarda-roupa Estragado', 74500);
INSERT INTO product (name, price) VALUES ('Lava-louças Necessário', 73380);
INSERT INTO product (name, price) VALUES ('Adulto Péssimo', 64419);
INSERT INTO product (name, price) VALUES ('Geladeira Espetacular', 86551);
INSERT INTO product (name, price) VALUES ('Geladeira Magnífico', 69345);
INSERT INTO product (name, price) VALUES ('Cafeteira Estonteante', 31105);
INSERT INTO product (name, price) VALUES ('Pizza Indispensável', 5786);
INSERT INTO product (name, price) VALUES ('Adolescente Fantástico', 10367);
INSERT INTO product (name, price) VALUES ('Smart TV Recondicionado', 59837);
INSERT INTO product (name, price) VALUES ('Máquina de lavar Extraordinário', 90212);
INSERT INTO product (name, price) VALUES ('Churrasqueira elétrica Inutilizável', 84391);
INSERT INTO product (name, price) VALUES ('Sofá Maravilhoso', 57552);
INSERT INTO product (name, price) VALUES ('Fogão a lenha Espetacular', 1911);
INSERT INTO product (name, price) VALUES ('Guarda-roupa Dispensável', 56772);
INSERT INTO product (name, price) VALUES ('Sashimi Fantástico', 10255);
INSERT INTO product (name, price) VALUES ('Fogão a gás Magnífico', 34489);
INSERT INTO product (name, price) VALUES ('Fogão por indução Irrelevante', 90478);
INSERT INTO product (name, price) VALUES ('Fogão elétrico Necessário', 51446);
INSERT INTO product (name, price) VALUES ('Fogão a gás Recertificado', 55699);
INSERT INTO product (name, price) VALUES ('Torradeira Deslumbrante', 15251);
INSERT INTO product (name, price) VALUES ('Sofá Irrelevante', 20116);
INSERT INTO product (name, price) VALUES ('Ar-condicionado Incrível', 68132);
INSERT INTO product (name, price) VALUES ('Grill Novo', 12043);
INSERT INTO product (name, price) VALUES ('Forno micro-ondas Desimportante', 28456);
INSERT INTO product (name, price) VALUES ('Tablet Quebrado', 9490);
INSERT INTO product (name, price) VALUES ('Microondas Irrelevante', 33702);
INSERT INTO product (name, price) VALUES ('Aspirador de pó Obrigatório', 50036);
INSERT INTO product (name, price) VALUES ('Sanduicheira Recondicionado', 12614);
INSERT INTO product (name, price) VALUES ('Uva Desimportante', 72447);
INSERT INTO product (name, price) VALUES ('Relógio de bolso Fantástico', 72464);
INSERT INTO product (name, price) VALUES ('Maçã Desimportante', 73847);
INSERT INTO product (name, price) VALUES ('Relógio de mesa Obrigatório', 7814);
INSERT INTO product (name, price) VALUES ('Maçã Novo', 80942);
INSERT INTO product (name, price) VALUES ('Fogão a lenha Restaurado', 5021);
INSERT INTO product (name, price) VALUES ('Cafeteira Inutilizável', 78020);
INSERT INTO product (name, price) VALUES ('Ar-condicionado Recondicionado', 23790);
INSERT INTO product (name, price) VALUES ('Fogão de embutir Perfeito', 86049);
INSERT INTO product (name, price) VALUES ('Cachorro-quente Irrelevante', 52973);
INSERT INTO product (name, price) VALUES ('Fogão a gás Semi-novo', 45901);
INSERT INTO product (name, price) VALUES ('Televisão Magnífico', 87202);
INSERT INTO product (name, price) VALUES ('Lava-louças Danificado', 17441);
INSERT INTO product (name, price) VALUES ('Adolescente Sensacional', 5632);
INSERT INTO product (name, price) VALUES ('Sashimi Espetacular', 6527);
INSERT INTO product (name, price) VALUES ('Microondas Magnífico', 31136);
INSERT INTO product (name, price) VALUES ('Churrasqueira elétrica Restaurado', 28844);
INSERT INTO product (name, price) VALUES ('Secadora de roupas Fantástico', 22649);
INSERT INTO product (name, price) VALUES ('Relógio de bolso Danificado', 91249);
INSERT INTO product (name, price) VALUES ('Smartwatch Indispensável', 12949);
INSERT INTO product (name, price) VALUES ('Churrasqueira elétrica Restaurado', 49323);
INSERT INTO product (name, price) VALUES ('Notebook Supérfluo', 17466);
INSERT INTO product (name, price) VALUES ('Smart TV Deslumbrante', 7821);
INSERT INTO product (name, price) VALUES ('Fritadeira elétrica Quebrado', 52686);
INSERT INTO product (name, price) VALUES ('Cama Danificado', 27703);
INSERT INTO product (name, price) VALUES ('Forno elétrico Obrigatório', 32773);
INSERT INTO product (name, price) VALUES ('Liquidificador Fundamental', 54402);
INSERT INTO product (name, price) VALUES ('Fogão industrial Desimportante', 83358);
INSERT INTO product (name, price) VALUES ('Sashimi Novo', 6322);
INSERT INTO product (name, price) VALUES ('Batedeira Magnífico', 20894);
INSERT INTO product (name, price) VALUES ('Máquina de lavar Usado', 58730);
INSERT INTO product (name, price) VALUES ('Playstation 5 Usado', 29314);
INSERT INTO product (name, price) VALUES ('Xbox Series X Quebrado', 50092);
INSERT INTO product (name, price) VALUES ('Goiaba Recertificado', 24057);
